Handling log roll for multiple log files.
Also handles logs already rolled by their mods correctly.

diff --git a/minecraft b/minecraft
--- a/minecraft
+++ b/minecraft
@@ -207,6 +207,34 @@ mc_stop() {
 	echo "$SERVICE is now shut down."
 }
 
+log_roll() {
+	# Moves and Gzips the logfiles into a directory
+	shopt -s extglob
+	path=`datepath $LOGPATH/logs_`
+	as_user "mkdir -p $path"
+	
+	for FILE in $(ls $MCPATH/*.log)
+	do
+		as_user "cp $FILE $path"
+		# only if previous command was successful
+		if [ $? -eq 0 ]; then
+			if [[ "$FILE" = @(*-+([0-9]).log) && "$FILE" = !(*-0.log) ]]
+			# some mods already roll logs. remove all but the most recent file
+			# which ends with -0.log
+			then
+				as_user "rm $FILE"
+			else
+			# truncate the existing log without restarting server
+				as_user "cp /dev/null $FILE"
+				as_user "echo \"Previous logs rolled to $path\" > $FILE"
+			fi
+		else    
+			echo "Failed to rotate log from $FILE into $path"
+		fi
+	done
+	as_user "gzip -r $path"
+}
+
 get_worlds() {
 	SAVEIFS=$IFS
 	IFS=$(echo -en "\n\b")
@@ -755,20 +783,7 @@ case "$1" in
 		fi
 		;;
 	log-roll)
-		# Moves and Gzips the logfile
-		if [ ! -d $LOGPATH ]; then
-			as_user "mkdir -p $LOGPATH"
-		fi
-		path=`datepath $LOGPATH/server_ .log.gz .log`
-		as_user "cp $MCPATH/server.log $path && gzip $path"
-		# only if previous command was successful
-		if [ $? -eq 0 ]; then
-			# turnacate the existing log without restarting server
-			as_user "cp /dev/null $MCPATH/server.log"
-			as_user "echo \"Previous logs rolled to $path\" > $MCPATH/server.log "
-		else    
-			echo "Failed to rotate logs to $LOGPATH/server_$path.log.gz"
-		fi
+		log_roll
 		;;
 	last)
 		# Greps for recently logged in users
